name: "Build Project"

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.101' 

      - name: Restore
        run: dotnet Restore

      - name: Build
        run: dotnet build --no-restore -c Release
        
